[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*
filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestUnhandledThreadExceptionWarning
addopts = -ra
