########################################
#             基本配置              #
########################################

# 游戏根目录的路径
game_path: ''

# 翻译工程文件保存位置 (必须已存在)
save_path: ''

# 要翻译的 xlsx 文件保存位置 (必须已存在)
data_path: ''

# 翻译后的 xlsx 文件路径 (如果不注入游戏，可以先不改)
# 游戏版本更新时，此为旧版翻译文件的路径
translation_path: ''

# 导出注入翻译后的 data 文件存放位置
output_path: ''

# 是否为日文游戏 (1: 是, 0: 否)。非日文游戏必须改为 0
ja: 1

# 水印 (添加到游戏标题, 不设置则留空或设为 0)
mark: 0


########################################
#            自定义提取规则           #
########################################

# 提取名字时，排除地址中包含以下内容的文本
# * 代表通配符, 如 'vents.*name' 排除包含 'vents' 和 'name' 的地址
NameWithout:
  - 'vents.*name'
  - 'Troops.*name'
  - 'Skills.*name'
  - 'Items.*name'
  - 'States.*name'

# 特殊文本提取规则 (用于处理特殊格式的文本)
# 格式: 'code': {'标识文本': '正则表达式'}
#  - 'code':  需要特殊处理的文本的 code
#  - '标识文本':  用于识别需要提取的文本的特征字符串 (如果不需要，设为 "空")
#  - '正则表达式': 用于提取文本的正则表达式 (用中文句号代替英文单引号)
sptext:
  '355': { 'addText': '[^a-zA-z0-9(),。]+' }
  '356': { 'addLog': '[^a-zA-z0-9(),。]+' }


# 读取文本时，只读取 code 为以下内容的文本 (-1 代表无 code)
ReadCode:
  - '-1'
  - '401'
  - '405'
  - '101'
  - '102'
  - '105'
  - '320'
  - '324'

# 文本求和: 将连续的以下 code 的文本合并
sumcode:
  - '401'
  - '405'

# 地址黑名单: 包含以下内容的地址不会被翻译
BlackDir:
  - 'vents.*name'
  - 'Troops.*name'
  - 'System.*switches'
  - 'System.*variables'
  - 'SrcEventIdOrName'

# code 黑名单: 以下 code 的文本不会被翻译
BlackCode: []

# 文件黑名单: 不读取以下文件
BlackFiles:
  - 'Animations.json'
  - 'MapInfos.json'
  - 'Tilesets.json'

########################################
#          进阶自定义 (可选)          #
########################################

# 自动换行设置
line_length: 40  # 每行字数 (-1: 使用 JS 插件, 0: 不换行)
auto_linefeed_js: '自动换行.js'  # 自动换行 JS 插件文件名

# note 类文本处理 (用于处理图鉴等)
note_percent: 0.2  #  <: 之间的长度占比小于此值时应用原文

# 处理文件名时，提取以下分隔符内的文本
codewithnames:
  - - '['
    - ']'
  - - '"'
    - '"'
  - - '<'
    - '>'

# 自定义翻译文件表头与列号 (可选, 用于从外部xlsx导入)
source_header: "Original Text"      # 原文的表头, 默认"Original Text"
translation_header: "Initial"  #  译文的表头, 默认"Initial"
source_column: 0   # 原文所在列号， 默认第0列
translation_column: 1  # 译文所在列号, 默认第1列

########################################
#            程序内部配置             #
########################################

#  (通常不需要修改)

need2check_filename: 'need2check.json'  # 文件名检查结果文件名

project_data_dir: 'data'      # 工程文件数据目录名
project_dir_name: '翻译工程文件'  # 翻译工程文件名
